### ISSUE TITLE
Test on all default Mapbox styles

### ISSUE THREAD

**Issue by planemad** [planemad/mapbox-gl-js-boundaries#1]
Switch India borders on all these styles:
- [x] mapbox://styles/mapbox/streets-v9
- [x] mapbox://styles/mapbox/outdoors-v9
- [x] mapbox://styles/mapbox/light-v9
- [ ] mapbox://styles/mapbox/dark-v9
- [x] mapbox://styles/mapbox/satellite-streets-v9

cc @ajashton

**Comment by planemad** [comment]
Currently the plugin checks for `admin-2-boundaries` and `admin-2-dispute` layer to be present in the style to work correctly. Different layer names in styles can cause this to break.

**Comment by planemad** [comment]
Tested on all styles

![untitled3](https://cloud.githubusercontent.com/assets/126868/15406549/a36f20ca-1e24-11e6-80b8-557cc731e8a3.gif)

Theres some issue with dark-v9 where there is some unusual behavior where the boundary background line layer hides and shows inconsistently.

![untitled3](https://cloud.githubusercontent.com/assets/126868/15406661/0397ecde-1e25-11e6-9c70-4b4880894a22.gif)

**Comment by 1ec5** [comment]
#6 would make this plugin style-agnostic, so it wouldn’t be necessary to test on specific styles.
