### ISSUE TITLE
Hide only disputed boundaries of target country

### ISSUE THREAD

**Issue by planemad** [planemad/mapbox-gl-js-boundaries#2]
Currently disputed boundaries worldwide are hidden causing gaps in borders.

A better approach is to add the new borders on top of the disputed borders covering up the dotted lines There does not seem to be a mapbox-gl-js method to add a layer _after_ another layer with a known id `admin-2-boundaries-dispute`.

Alternative is to hide only select sections of the disputed boundaries by country code `["!in", "iso_3166_1", "IN", "CN-IN", "IN-PK"]`

https://www.mapbox.com/mapbox-gl-js/api/#Map#addLayer

**Comment by 1ec5** [comment]
Once we upgrade to Streets source v8 (#4), we’ll be able to show the target country’s claim lines, dotting the disputed lines while avoiding gaps.
