### ISSUE TITLE
How do I achieve this using leaflet?

### ISSUE THREAD

**Issue by akshaykumarbu** [planemad/mapbox-gl-js-boundaries#3]
Hi,

I am new to mapBox. I had fixed this using normal mapBox API as in the instructions. But now, I have moved my application to Leaflet. How do I add source and get this fix for disputed boundaries for India? Would be great if you can provide a sample code using leaflet. Thanks.

**Comment by akshaykumarbu** [comment]
@planemad, would you be able to help here?

**Comment by planemad** [comment]
@akbu2498 i'm not completely familiar with leaflet, but its likely that you will not be able to use the Mapbox source as easily with it to get this result.

You can try adding a custom GeoJSON overlay https://leafletjs.com/reference-1.3.0.html#geojson and use [this export->GeoJSON for the extra boundaries](http://overpass-turbo.eu/s/voe) in your map. You will need to add style properties in leaflet to closely match the basemap style.
