### ISSUE TITLE
Upgrade to Mapbox Streets v8 with worldviews

### ISSUE THREAD

**Issue by 1ec5** [planemad/mapbox-gl-js-boundaries#4]
This plugin currently relies on one of @planemad’s tilesets for boundaries. Mapbox Streets source v8 comes with a limited set of [worldviews](https://blog.mapbox.com/dynamically-change-disputed-national-borders-2c3f218f563d) that this plugin could filter on. But first it needs to be upgraded to work with Streets source v8 and expressions.

**Comment by dasulit** [comment]
In lieu of upgrading, we're archiving this repo as there are no plans to work on this project; Mapbox Streets v8 is the recommended place to start for working with worldviews.
