### ISSUE TITLE
Automatically choose boundaries by browser region

### ISSUE THREAD

**Issue by 1ec5** [planemad/mapbox-gl-js-boundaries#5]
This plugin would be more versatile if it could detect the user’s preferred set of boundaries based on the country code in `navigator.language` or `navigator.languages`.

/cc @planemad

**Comment by 1ec5** [comment]
[locale-utils](https://github.com/mapbox/locale-utils/) could be useful for parsing out the country code.

**Comment by dasulit** [comment]
Closing as there are no plans to work on this project (@1ec5 happy to chat if you object)
