### ISSUE TITLE
Find layers by source layer

### ISSUE THREAD

**Issue by 1ec5** [planemad/mapbox-gl-js-boundaries#6]
This plugin currently hard-codes layer IDs like `admin-2-boundaries-bg` that may not be present in every style that’s based on the Mapbox Streets source. Instead, it should apply the changes to any layer that uses the [`admin`](https://www.mapbox.com/vector-tiles/mapbox-streets-v8/#admin) source layer. This change would make the plugin more versatile, with less configuration required, and unblock worldview adoption: #4.

/cc @planemad

**Comment by dasulit** [comment]
Closing as there are no plans to work on this project (@1ec5 happy to chat if you object)
